# Generated by Django 3.1.7 on 2021-04-14 08:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210409_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phno',
            field=models.CharField(max_length=10, null=True, validators=[accounts.models.phone_validator]),
        ),
    ]
