# Generated by Django 3.1.7 on 2021-04-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cart_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='quant',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
