# Generated by Django 3.1.7 on 2021-04-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_orderitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-ordered_at']},
        ),
    ]
